### ISSUE TITLE
Sections and articles have no padding or margin?

### ISSUE THREAD

**Issue by EternityForest** [bigskysoftware/missing#35]
I am working on an experimental port of a webapp, and I'm finding that out of the box, sections and articles are cramped.  As semantic elements, should these have a bit more styling OOB?

**Comment by dz4k** [comment]
Sections and articles usually start with headings, which have top margins. Some HTML generating tools (e.g. Asciidoc, Pandoc in some configurations) automatically insert section tags based on headings. This means adding margin to sections by default would lead to those documents being unevenly spaced.

Section and article are elements with extremely broad usage, and no behavior that would guide their appearance. My experimentation in the early stages of missing.css development showed any styling we add would break some valid document.

If you want, you can use the `margin-block` class to add margin in the block axis (the vertical axis, in languages written horizontally).

**Comment by dz4k** [comment]
Closing this issue since I don't currently plan to implement this, but I am still open to discussion if you (or anyone else) have ideas on how we could style sections and articles without breaking valid documents. Our discord channel (https://htmx.org/discord **#missing-css**) is currently the most convenient medium for discussion.
